# Generated by Django 4.2.25 on 2025-10-31 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WashingMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('machine_type', models.CharField(choices=[('washer', 'Lave-linge'), ('dryer', 'Sèche-linge')], default='washer', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('in_use', 'En cours d’utilisation'), ('maintenance', 'En maintenance'), ('out_of_order', 'Hors service')], default='available', max_length=20)),
                ('capacity_kg', models.DecimalField(decimal_places=1, help_text='Capacité en kg', max_digits=4)),
                ('price_per_cycle', models.DecimalField(decimal_places=2, help_text='Prix par cycle (€)', max_digits=6)),
                ('location', models.CharField(blank=True, help_text='Emplacement dans la laverie (ex: rangée A, machine 3)', max_length=200)),
                ('last_maintenance_date', models.DateField(blank=True, null=True)),
                ('next_maintenance_date', models.DateField(blank=True, null=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('is_connected', models.BooleanField(default=True, help_text='Indique si la machine envoie des données en ligne')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines_in_use', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
